DROP TABLE IF EXISTS billionaires;
 
CREATE TABLE VEHICLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  model VARCHAR(250) NOT NULL,
  make VARCHAR(250) NOT NULL,
  vin VARCHAR(250) NOT NULL,
  color VARCHAR(250) NOT NULL,
  year  VARCHAR(250) NOT NULL
);